# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\QZhao\Desktop\hea\app.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BattleMage = QtWidgets.QPushButton(self.centralwidget)
        self.BattleMage.setGeometry(QtCore.QRect(40, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BattleMage.setFont(font)
        self.BattleMage.setObjectName("BattleMage")
        self.M_Crusader = QtWidgets.QPushButton(self.centralwidget)
        self.M_Crusader.setGeometry(QtCore.QRect(40, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.M_Crusader.setFont(font)
        self.M_Crusader.setObjectName("M_Crusader")
        self.F_Laucher = QtWidgets.QPushButton(self.centralwidget)
        self.F_Laucher.setGeometry(QtCore.QRect(140, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.F_Laucher.setFont(font)
        self.F_Laucher.setObjectName("F_Laucher")
        self.FM_Crusader = QtWidgets.QPushButton(self.centralwidget)
        self.FM_Crusader.setGeometry(QtCore.QRect(140, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FM_Crusader.setFont(font)
        self.FM_Crusader.setObjectName("FM_Crusader")
        self.SwiftMaster = QtWidgets.QPushButton(self.centralwidget)
        self.SwiftMaster.setGeometry(QtCore.QRect(140, 220, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SwiftMaster.setFont(font)
        self.SwiftMaster.setObjectName("SwiftMaster")
        self.SoulBender = QtWidgets.QPushButton(self.centralwidget)
        self.SoulBender.setGeometry(QtCore.QRect(40, 220, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SoulBender.setFont(font)
        self.SoulBender.setAutoRepeatInterval(98)
        self.SoulBender.setObjectName("SoulBender")
        self.Luke = QtWidgets.QPushButton(self.centralwidget)
        self.Luke.setGeometry(QtCore.QRect(680, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Luke.setFont(font)
        self.Luke.setObjectName("Luke")
        self.Tayberrs = QtWidgets.QPushButton(self.centralwidget)
        self.Tayberrs.setGeometry(QtCore.QRect(680, 220, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Tayberrs.setFont(font)
        self.Tayberrs.setObjectName("Tayberrs")
        self.DC = QtWidgets.QPushButton(self.centralwidget)
        self.DC.setGeometry(QtCore.QRect(680, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DC.setFont(font)
        self.DC.setObjectName("DC")
        self.Assult = QtWidgets.QPushButton(self.centralwidget)
        self.Assult.setGeometry(QtCore.QRect(580, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Assult.setFont(font)
        self.Assult.setObjectName("Assult")
        self.Anton = QtWidgets.QPushButton(self.centralwidget)
        self.Anton.setGeometry(QtCore.QRect(580, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Anton.setFont(font)
        self.Anton.setObjectName("Anton")
        self.Beast = QtWidgets.QPushButton(self.centralwidget)
        self.Beast.setGeometry(QtCore.QRect(580, 220, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Beast.setFont(font)
        self.Beast.setObjectName("Beast")
        self.Complete = QtWidgets.QPushButton(self.centralwidget)
        self.Complete.setGeometry(QtCore.QRect(370, 90, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Complete.setFont(font)
        self.Complete.setObjectName("Complete")
        self.CurrentTimeLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.CurrentTimeLCD.setGeometry(QtCore.QRect(240, 30, 261, 61))
        self.CurrentTimeLCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CurrentTimeLCD.setAutoFillBackground(False)
        self.CurrentTimeLCD.setDigitCount(8)
        self.CurrentTimeLCD.setObjectName("CurrentTimeLCD")
        self.CountDownLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.CountDownLCD.setGeometry(QtCore.QRect(240, 220, 261, 61))
        self.CountDownLCD.setObjectName("CountDownLCD")
        self.Complete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Complete_2.setGeometry(QtCore.QRect(240, 90, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Complete_2.setFont(font)
        self.Complete_2.setObjectName("Complete_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        self.menuNothinMenu = QtWidgets.QMenu(self.menubar)
        self.menuNothinMenu.setObjectName("menuNothinMenu")
        self.menu = QtWidgets.QMenu(self.menuNothinMenu)
        self.menu.setObjectName("menu")
        self.menuI_SAID_NOTHING = QtWidgets.QMenu(self.menu)
        self.menuI_SAID_NOTHING.setObjectName("menuI_SAID_NOTHING")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEXIT = QtWidgets.QAction(MainWindow)
        self.actionEXIT.setObjectName("actionEXIT")
        self.menuI_SAID_NOTHING.addAction(self.actionEXIT)
        self.menu.addAction(self.menuI_SAID_NOTHING.menuAction())
        self.menuNothinMenu.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuNothinMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BattleMage.setText(_translate("MainWindow", "Battle\n"
"Mage"))
        self.M_Crusader.setText(_translate("MainWindow", "Male\n"
"Crusader"))
        self.F_Laucher.setText(_translate("MainWindow", "Female\n"
"Laucher"))
        self.FM_Crusader.setText(_translate("MainWindow", "Female\n"
"Crusader"))
        self.SwiftMaster.setText(_translate("MainWindow", "Swift\n"
"Master"))
        self.SoulBender.setText(_translate("MainWindow", "Soul\n"
"Bender"))
        self.Luke.setText(_translate("MainWindow", "卢克"))
        self.Tayberrs.setText(_translate("MainWindow", "泰波\n"
"尔斯"))
        self.DC.setText(_translate("MainWindow", "黎明"))
        self.Assult.setText(_translate("MainWindow", "强袭"))
        self.Anton.setText(_translate("MainWindow", "安图恩"))
        self.Beast.setText(_translate("MainWindow", "魔兽"))
        self.Complete.setText(_translate("MainWindow", "Complete"))
        self.Complete_2.setText(_translate("MainWindow", "Start"))
        self.menuNothinMenu.setTitle(_translate("MainWindow", "NothinMenu"))
        self.menu.setTitle(_translate("MainWindow", "????"))
        self.menuI_SAID_NOTHING.setTitle(_translate("MainWindow", "I SAID NOTHING"))
        self.actionEXIT.setText(_translate("MainWindow", "EXIT"))

